"use client";
import { Activity, Bot, CarFront, Clock3, Siren, Waypoints } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { HealthChart, ToolsChart, TrendChart } from "@/components/dashboard-charts";
import { Badge, Metric, PageHeader } from "@/components/page-kit";
import { tasks } from "@/lib/demo-data";
import { getDashboardSummary, listTasks } from "@/lib/api";
export default function Dashboard() { const {data:s}=useQuery({queryKey:["dashboard"],queryFn:getDashboardSummary,refetchInterval:10000}); const {data:taskData}=useQuery({queryKey:["tasks","recent"],queryFn:listTasks,refetchInterval:5000}); return <><PageHeader title="系统总览" description="车辆、Agent 任务与基础设施的实时运行概览" action={<button className="button secondary">今日实时数据</button>}/><section className="metric-grid"><Metric label="在线车辆" value={String(s?.online_vehicles??"—")} meta="已接入车辆" icon={<CarFront/>}/><Metric label="今日 Agent 任务" value={String(s?.tasks_today??"—")} meta="MySQL 实时聚合" icon={<Bot/>}/><Metric label="任务成功率" value={s?`${s.success_rate.toFixed(1)}%`:"—"} meta="目标 ≥ 95%" icon={<Activity/>}/><Metric label="平均响应时间" value={s?`${Math.round(s.average_response_ms)}ms`:"—"} meta="完成任务平均值" icon={<Clock3/>}/><Metric label="故障车辆" value={String(s?.fault_vehicles??"—")} meta="等待诊断数据源" icon={<Siren/>}/><Metric label="消息积压" value={s?.queue_metric_source==="not_configured"?"N/A":String(s?.rabbitmq_backlog??0)} meta="管理指标待配置" icon={<Waypoints/>}/></section><section className="dashboard-grid"><article className="panel wide"><div className="panel-head"><div><h2>Agent 任务趋势</h2><p>成功与失败任务数量</p></div><Badge>实时</Badge></div><TrendChart/></article><article className="panel"><div className="panel-head"><div><h2>车辆健康状态</h2><p>当前车辆分布</p></div></div><HealthChart/><div className="legend"><span><i className="blue"/>健康</span><span><i className="amber"/>需关注</span><span><i className="red"/>故障</span></div></article><article className="panel"><div className="panel-head"><div><h2>工具调用</h2><p>今日共 {s?.tool_calls_today??0} 次</p></div></div><ToolsChart/></article><article className="panel wide"><div className="panel-head"><div><h2>最近 Agent 任务</h2><p>来自 Go API 的真实任务记录</p></div><a href="/tasks">查看全部</a></div><TaskTable items={taskData?.items}/></article></section></>; }
export function TaskTable({items}:{items?:import("@/lib/api").AgentTask[]}){const rows=items?.slice(0,5);return <div className="table-wrap"><table><thead><tr><th>任务</th><th>状态</th><th>当前步骤</th><th>工具</th><th>结果</th></tr></thead><tbody>{rows?.length?rows.map(t=><tr key={t.id}><td><b>{t.command}</b><small>{t.id}</small></td><td><Badge tone={t.status==="failed"?"red":t.status==="finished"?"green":"blue"}>{t.status}</Badge></td><td>{t.status==="finished"?"任务完成":t.status==="failed"?"执行失败":"Agent 执行中"}</td><td>{t.tool_calls?.length??0}</td><td>{t.result||t.error_message||"—"}</td></tr>):tasks.slice(0,2).map(t=><tr key={t.id}><td><b>暂无真实任务</b><small>在 Agent 页面提交任务后显示</small></td><td><Badge tone="gray">empty</Badge></td><td>等待任务</td><td>0</td><td>—</td></tr>)}</tbody></table></div>}
