"use client";
import { FormEvent, useState } from "react";
import { Bot, CarFront, Check, ChevronRight, MessageSquarePlus, Navigation, Search, Send, Thermometer, Zap } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { createTask, prepareVehicle, AgentTask, watchTask } from "@/lib/api";
import { Badge, PageHeader } from "@/components/page-kit";
const prompt="帮我找到附近最近的充电站，并结合当前续航规划路线。";
export default function AgentPage(){const {data:vehicle,error}=useQuery({queryKey:["vehicle"],queryFn:prepareVehicle});const [command,setCommand]=useState(prompt);const [task,setTask]=useState<AgentTask|null>(null);const [busy,setBusy]=useState(false);async function submit(e:FormEvent){e.preventDefault();if(!vehicle||!command.trim())return;setBusy(true);try{const current=await createTask(vehicle.id,command);setTask(current);await watchTask(current.id,setTask)}finally{setBusy(false)}}return <><PageHeader title="智能座舱 Agent" description="通过自然语言编排车辆能力，并观察每一步工具调用" action={<Badge tone="green">Agent 服务在线</Badge>}/><div className="agent-layout"><aside className="conversation-list"><button className="button full"><MessageSquarePlus size={16}/>新建会话</button><div className="mini-search"><Search size={15}/>搜索历史会话</div><label>当前车辆</label><div className="vehicle-select"><span className="car-icon"><CarFront/></span><div><b>{vehicle?.vehicle_model??"连接中"}</b><small>{vehicle?.vin??"正在获取车辆"}</small></div><ChevronRight size={16}/></div><label>今天</label>{["规划最近充电路线","调整座舱温度","查询车辆健康状态"].map((x,i)=><button className={`history ${i===0?"selected":""}`} key={x}><span>{x}</span><small>{i===0?"刚刚":`${i+1} 小时前`}</small></button>)}</aside><section className="chat"><div className="chat-head"><div><b>规划最近充电路线</b><span>AutoPilot S7 · 沪A·A1027</span></div><Badge>{busy?"执行中":"可用"}</Badge></div><div className="messages"><div className="message user">{command}</div><div className="message assistant"><div className="bot-avatar"><Bot size={17}/></div><div><b>AutoPilot Agent</b>{task?<p>{task.result||task.error_message||"任务已进入队列，正在规划执行步骤…"}</p>:<p>我会先读取车辆实时状态，再查询附近充电站并计算最优路线。你可以发送下方示例任务开始演示。</p>}<Execution task={task} busy={busy}/></div></div></div><form className="composer" onSubmit={submit}><textarea value={command} onChange={e=>setCommand(e.target.value)} placeholder="向智能座舱 Agent 发送任务…"/><button disabled={!vehicle||busy}><Send size={17}/></button><span>Enter 发送 · Shift + Enter 换行</span></form></section><aside className="vehicle-context"><h2>车辆状态</h2><div className="vehicle-hero"><div className="vehicle-shape"><CarFront size={52}/></div><b>{vehicle?.vehicle_model??"AutoPilot S7"}</b><span><i/>在线 · {vehicle?.status.location??"上海市浦东新区"}</span></div><div className="context-stats"><div><Zap/><span>剩余电量</span><b>{vehicle?.status.battery??72}%</b></div><div><Navigation/><span>剩余续航</span><b>386 km</b></div><div><Thermometer/><span>车内温度</span><b>{vehicle?.status.temperature??24}°C</b></div></div><h2>工具调用时间线</h2><div className="compact-trace">{(task?.tool_calls??[]).map(call=><div key={call.id}><Check/><span><b>{call.tool_name}</b><small>{call.latency_ms} ms</small></span></div>)}{!task?.tool_calls?.length&&<p>{error instanceof Error?error.message:"任务开始后在此展示实时轨迹"}</p>}</div></aside></div></>}
function Execution({task,busy}:{task:AgentTask|null,busy:boolean}){if(!task&&!busy)return null;const steps=["获取车辆状态","查询附近充电站","计算推荐路线","启动车辆导航"];return <div className="execution"><div className="execution-head"><span><i/>Agent 执行过程</span><small>{task?.status??"planning"}</small></div>{steps.map((s,i)=><div className="exec-step" key={s}><span className={task?.status==="finished"||i<(task?.tool_calls?.length??0)?"done":""}>{task?.status==="finished"||i<(task?.tool_calls?.length??0)?<Check size={12}/>:i+1}</span><b>{s}</b><small>{task?.tool_calls?.[i]?.latency_ms?`${task.tool_calls[i].latency_ms} ms`:"等待执行"}</small></div>)}</div>}
